### ISSUE TITLE
Eliminar comentarios

### ISSUE THREAD

**Issue by Nidev-lab** [JuaniLavenia/proyecto-web-final-backend#11]
Buenas! como va? encontre algunos comentarios en el codigo,
![image](https://github.com/JuaniLavenia/proyecto-web-final-backend/assets/53904695/7a7029c2-d760-4891-980c-98a5585403cf)
Recuerden, los comentarios no estan vistos como una buena practica , pero en si el codigo comentado es mucho menos aceptado.

Cualquier cosita podes contactarme a [nicogonzalez2008@gmail.com](mailto:nicogonzalez2008@gmail.com) o por el slack de RollingCode

**Comment by JuaniLavenia** [comment]
Hola! Perfecto, ya elimine todas las lineas comentadas, gracias por el feedback.
